import requests
import json
import os

def perform_web_search(query, count=10):
    """
    Since we can't call the built-in web_search tool from Python directly 
    without an agent context, we use this helper. 
    In the agent's environment, we'll try to use a local fallback if needed,
    but here we expect the agent to have already performed the search 
    and passed the results, or we mock it for development.
    
    Actually, for the agent, the best way is to provide a results file.
    """
    # For now, we look for a local cache file generated by the agent before calling.
    cache_path = "data/search_cache.json"
    if os.path.exists(cache_path):
        with open(cache_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    return []
